### ISSUE TITLE
TypeMismatch Error

### ISSUE THREAD

**Issue by shivang94** [UBOdin/mimir#249] opened 2017-07-28 00:49 UTC
Seems to be coming from the typechecker in the DST function in GeoFunctions.scala
Error can be seen when running explain on CURE query.

**Comment by okennedy** [comment] 2017-07-31 20:32
Can't reproduce.  Running `testOnly mimir.demo.CureScenario` on `CurePrioritize`:
```
[info] CureScenario
[info]
[info] The CURE Scenario should
[info]   + Load 'test/data/cureSource.csv'
[info]   + Load 'test/data/cureLocations.csv'
[info]   + Load 'test/data/curePorts.csv'
[info]   + Select from the source table
[info]   + Create the source MV Lens
[info]   + Create the locations MV Lens
[info]   + Run the CURE Query
[info]   + Test Prioritizer
[info]
[info]
[info] Total for specification CureScenario
[info] Finished in 3 seconds, 193 ms
[info] 8 examples, 0 failure, 0 error
[info]
[info] Passed: Total 8, Failed 0, Errors 0, Passed 8
```
Can you provide more detailed reproduction steps or a test case?

**Comment by shivang94** [comment] 2017-07-31 20:54
I just ran EXPLAIN on the CURE query on the Mimir command line interface and got the following output:
```------ Raw Query ------
PROJECT[BILL_OF_LADING_NBR <= SRC_BILL_OF_LADING_NBR, "SRC_IMO" <= SRC_IMO_CODE, "VESSEL_LAT" <= LOC_LAT, "VESSEL_LON" <= LOC_LON, "PORT_LAT" <= PORTS_LAT, "PORT_LON" <= PORTS_LON, "SRC_DATE" <= DATE(SRC_DATE), "DISTANCE" <= DST(LOC_LON, LOC_LAT, PORTS_LON, PORTS_LAT), "SPEED" <= SPEED(DST(LOC_LON, LOC_LAT, PORTS_LON, PORTS_LAT), SRC_DATE, NULL)](
  SELECT[ (SPEED(DST(LOC_LON, LOC_LAT, PORTS_LON, PORTS_LAT), SRC_DATE, NULL)>100) ](
    SELECT[ (SRC_PORT_OF_ARRIVAL=PORTS_PORT) ](
      JOIN(
        SELECT[ (SRC_IMO_CODE=LOC_IMO_CODE) ](
          JOIN(
            PROJECT[SRC_DATE <= DATE, SRC_MONTH <= MONTH, SRC_CONSIGNEE_DECLARED <= CONSIGNEE_DECLARED, SRC_CONSIGNEE_DECLARED_ADDRESS <= CONSIGNEE_DECLARED_ADDRESS, SRC_SHIPPER_DECLARED <= SHIPPER_DECLARED, SRC_SHIPPER_ADDRESS <= SHIPPER_ADDRESS, SRC_NOTIFY_NAME <= NOTIFY_NAME, SRC_NOTIFY_ADDRESS <= NOTIFY_ADDRESS, SRC_CARRIER_CODE <= CARRIER_CODE, SRC_CARRIER <= CARRIER, SRC_BILL_MASTER_CARRIER <= BILL_MASTER_CARRIER, SRC_MASTER_CONSIGNEE_UNIFIED <= MASTER_CONSIGNEE_UNIFIED, SRC_MASTER_SHIPPER <= MASTER_SHIPPER, SRC_MASTER_NOTIFY <= MASTER_NOTIFY, SRC_CONSIGNEE_UNIFIED <= CONSIGNEE_UNIFIED, SRC_SHIPPER_UNIFIED <= SHIPPER_UNIFIED, SRC_CONSIGNEE_S_STATE <= CONSIGNEE_S_STATE, SRC_CONSIGNEE_S_CITY <= CONSIGNEE_S_CITY, SRC_CONSIGNEE_S_ZIP_CODE <= CONSIGNEE_S_ZIP_CODE, SRC_BILL_OF_LADING_NBR <= BILL_OF_LADING_NBR, SRC_MASTER_HOUSE <= MASTER_HOUSE, SRC_MODE_OF_TRANSPORT <= MODE_OF_TRANSPORT, SRC_ESTIMATED_DATE <= ESTIMATED_DATE, SRC_IN_BOND_ENTRY_TYPE <= IN_BOND_ENTRY_TYPE, SRC_SHORT_CONTAINER_DESCRIPTION <= SHORT_CONTAINER_DESCRIPTION, SRC_IMO_CODE <= IMO_CODE, SRC_HIGH_CUBE <= HIGH_CUBE, SRC_BILL_MASTER <= BILL_MASTER, SRC_HS_1 <= HS_1, SRC_HS_DESCRIPTION <= HS_DESCRIPTION, SRC_FOREIGN_DESTINATION <= FOREIGN_DESTINATION, SRC_US_REGION <= US_REGION, SRC_WORLD_REGION_BY_PORT_OF_DEPARTURE <= WORLD_REGION_BY_PORT_OF_DEPARTURE, SRC_COUNTRY_BY_PORT_OF_DEPARTURE <= COUNTRY_BY_PORT_OF_DEPARTURE, SRC_PORT_OF_DEPARTURE <= PORT_OF_DEPARTURE, SRC_STATE_OF_ARRIVAL_PORT <= STATE_OF_ARRIVAL_PORT, SRC_PORT_OF_ARRIVAL <= PORT_OF_ARRIVAL, SRC_VESSEL <= VESSEL, SRC_VESSEL_COUNTRY <= VESSEL_COUNTRY, SRC_FINAL_DESTINATION <= FINAL_DESTINATION, SRC_COUNTRY_OF_ORIGIN <= COUNTRY_OF_ORIGIN, SRC_WORLD_REGION_BY_COUNTRY_OF_ORIGIN <= WORLD_REGION_BY_COUNTRY_OF_ORIGIN, SRC_PLACE_OF_RECEIPT <= PLACE_OF_RECEIPT, SRC_COUNTRY_BY_PLACE_OF_RECEIPT <= COUNTRY_BY_PLACE_OF_RECEIPT, SRC_WORLD_REGION_BY_PLACE_OF_RECEIPT <= WORLD_REGION_BY_PLACE_OF_RECEIPT, SRC_QUANTITY <= QUANTITY, SRC_QUANTITY_UNIT <= QUANTITY_UNIT, SRC_WEIGHT <= WEIGHT, SRC_WEIGHT_UNIT <= WEIGHT_UNIT, SRC_MEASURE <= MEASURE, SRC_MEASURE_UNIT <= MEASURE_UNIT, SRC_CONTAINER_QUANTITY <= CONTAINER_QUANTITY, SRC_METRIC_TONS <= METRIC_TONS, SRC_CONTAINER_1 <= CONTAINER_1, SRC_PIECES_1 <= PIECES_1, SRC_DESCRIPTION_1 <= DESCRIPTION_1, SRC_HARMONIZED_1 <= HARMONIZED_1, SRC_MARKS_NUMBERS_1 <= MARKS_NUMBERS_1, SRC_HS_2 <= HS_2, SRC_CONTAINER_2 <= CONTAINER_2, SRC_PIECES_2 <= PIECES_2, SRC_DESCRIPTION_2 <= DESCRIPTION_2, SRC_HARMONIZED_2 <= HARMONIZED_2, SRC_MARKS_NUMBERS_2 <= MARKS_NUMBERS_2, SRC_HS_3 <= HS_3, SRC_CONTAINER_3 <= CONTAINER_3, SRC_PIECES_3 <= PIECES_3, SRC_DESCRIPTION_3 <= DESCRIPTION_3, SRC_HARMONIZED_3 <= HARMONIZED_3, SRC_MARKS_NUMBERS_3 <= MARKS_NUMBERS_3, SRC_HS_4 <= HS_4, SRC_CONTAINER_4 <= CONTAINER_4, SRC_PIECES_4 <= PIECES_4, SRC_DESCRIPTION_4 <= DESCRIPTION_4, SRC_HARMONIZED_4 <= HARMONIZED_4, SRC_MARKS_NUMBERS_4 <= MARKS_NUMBERS_4, SRC_HS_5 <= HS_5, SRC_CONTAINER_5 <= CONTAINER_5, SRC_PIECES_5 <= PIECES_5, SRC_DESCRIPTION_5 <= DESCRIPTION_5, SRC_HARMONIZED_5 <= HARMONIZED_5, SRC_MARKS_NUMBERS_5 <= MARKS_NUMBERS_5](
              CURESOURCE[] := (
                 PROJECT[DATE <= CAST(DATE, {{ CURESOURCE;0[][] }}), MONTH <= CAST(MONTH, {{ CURESOURCE;1[][] }}), CONSIGNEE_DECLARED <= CAST(CONSIGNEE_DECLARED, {{ CURESOURCE;2[][] }}), CONSIGNEE_DECLARED_ADDRESS <= CAST(CONSIGNEE_DECLARED_ADDRESS, {{ CURESOURCE;3[][] }}), SHIPPER_DECLARED <= CAST(SHIPPER_DECLARED, {{ CURESOURCE;4[][] }}), SHIPPER_ADDRESS <= CAST(SHIPPER_ADDRESS, {{ CURESOURCE;5[][] }}), NOTIFY_NAME <= CAST(NOTIFY_NAME, {{ CURESOURCE;6[][] }}), NOTIFY_ADDRESS <= CAST(NOTIFY_ADDRESS, {{ CURESOURCE;7[][] }}), CARRIER_CODE <= CAST(CARRIER_CODE, {{ CURESOURCE;8[][] }}), CARRIER <= CAST(CARRIER, {{ CURESOURCE;9[][] }}), BILL_MASTER_CARRIER <= CAST(BILL_MASTER_CARRIER, {{ CURESOURCE;10[][] }}), MASTER_CONSIGNEE_UNIFIED <= CAST(MASTER_CONSIGNEE_UNIFIED, {{ CURESOURCE;11[][] }}), MASTER_SHIPPER <= CAST(MASTER_SHIPPER, {{ CURESOURCE;12[][] }}), MASTER_NOTIFY <= CAST(MASTER_NOTIFY, {{ CURESOURCE;13[][] }}), CONSIGNEE_UNIFIED <= CAST(CONSIGNEE_UNIFIED, {{ CURESOURCE;14[][] }}), SHIPPER_UNIFIED <= CAST(SHIPPER_UNIFIED, {{ CURESOURCE;15[][] }}), CONSIGNEE_S_STATE <= CAST(CONSIGNEE_S_STATE, {{ CURESOURCE;16[][] }}), CONSIGNEE_S_CITY <= CAST(CONSIGNEE_S_CITY, {{ CURESOURCE;17[][] }}), CONSIGNEE_S_ZIP_CODE <= CAST(CONSIGNEE_S_ZIP_CODE, {{ CURESOURCE;18[][] }}), BILL_OF_LADING_NBR <= CAST(BILL_OF_LADING_NBR, {{ CURESOURCE;19[][] }}), MASTER_HOUSE <= CAST(MASTER_HOUSE, {{ CURESOURCE;20[][] }}), MODE_OF_TRANSPORT <= CAST(MODE_OF_TRANSPORT, {{ CURESOURCE;21[][] }}), ESTIMATED_DATE <= CAST(ESTIMATED_DATE, {{ CURESOURCE;22[][] }}), IN_BOND_ENTRY_TYPE <= CAST(IN_BOND_ENTRY_TYPE, {{ CURESOURCE;23[][] }}), SHORT_CONTAINER_DESCRIPTION <= CAST(SHORT_CONTAINER_DESCRIPTION, {{ CURESOURCE;24[][] }}), IMO_CODE <= CAST(IMO_CODE, {{ CURESOURCE;25[][] }}), HIGH_CUBE <= CAST(HIGH_CUBE, {{ CURESOURCE;26[][] }}), BILL_MASTER <= CAST(BILL_MASTER, {{ CURESOURCE;27[][] }}), HS_1 <= CAST(HS_1, {{ CURESOURCE;28[][] }}), HS_DESCRIPTION <= CAST(HS_DESCRIPTION, {{ CURESOURCE;29[][] }}), FOREIGN_DESTINATION <= CAST(FOREIGN_DESTINATION, {{ CURESOURCE;30[][] }}), US_REGION <= CAST(US_REGION, {{ CURESOURCE;31[][] }}), WORLD_REGION_BY_PORT_OF_DEPARTURE <= CAST(WORLD_REGION_BY_PORT_OF_DEPARTURE, {{ CURESOURCE;32[][] }}), COUNTRY_BY_PORT_OF_DEPARTURE <= CAST(COUNTRY_BY_PORT_OF_DEPARTURE, {{ CURESOURCE;33[][] }}), PORT_OF_DEPARTURE <= CAST(PORT_OF_DEPARTURE, {{ CURESOURCE;34[][] }}), STATE_OF_ARRIVAL_PORT <= CAST(STATE_OF_ARRIVAL_PORT, {{ CURESOURCE;35[][] }}), PORT_OF_ARRIVAL <= CAST(PORT_OF_ARRIVAL, {{ CURESOURCE;36[][] }}), VESSEL <= CAST(VESSEL, {{ CURESOURCE;37[][] }}), VESSEL_COUNTRY <= CAST(VESSEL_COUNTRY, {{ CURESOURCE;38[][] }}), FINAL_DESTINATION <= CAST(FINAL_DESTINATION, {{ CURESOURCE;39[][] }}), COUNTRY_OF_ORIGIN <= CAST(COUNTRY_OF_ORIGIN, {{ CURESOURCE;40[][] }}), WORLD_REGION_BY_COUNTRY_OF_ORIGIN <= CAST(WORLD_REGION_BY_COUNTRY_OF_ORIGIN, {{ CURESOURCE;41[][] }}), PLACE_OF_RECEIPT <= CAST(PLACE_OF_RECEIPT, {{ CURESOURCE;42[][] }}), COUNTRY_BY_PLACE_OF_RECEIPT <= CAST(COUNTRY_BY_PLACE_OF_RECEIPT, {{ CURESOURCE;43[][] }}), WORLD_REGION_BY_PLACE_OF_RECEIPT <= CAST(WORLD_REGION_BY_PLACE_OF_RECEIPT, {{ CURESOURCE;44[][] }}), QUANTITY <= CAST(QUANTITY, {{ CURESOURCE;45[][] }}), QUANTITY_UNIT <= CAST(QUANTITY_UNIT, {{ CURESOURCE;46[][] }}), WEIGHT <= CAST(WEIGHT, {{ CURESOURCE;47[][] }}), WEIGHT_UNIT <= CAST(WEIGHT_UNIT, {{ CURESOURCE;48[][] }}), MEASURE <= CAST(MEASURE, {{ CURESOURCE;49[][] }}), MEASURE_UNIT <= CAST(MEASURE_UNIT, {{ CURESOURCE;50[][] }}), CONTAINER_QUANTITY <= CAST(CONTAINER_QUANTITY, {{ CURESOURCE;51[][] }}), METRIC_TONS <= CAST(METRIC_TONS, {{ CURESOURCE;52[][] }}), CONTAINER_1 <= CAST(CONTAINER_1, {{ CURESOURCE;53[][] }}), PIECES_1 <= CAST(PIECES_1, {{ CURESOURCE;54[][] }}), DESCRIPTION_1 <= CAST(DESCRIPTION_1, {{ CURESOURCE;55[][] }}), HARMONIZED_1 <= CAST(HARMONIZED_1, {{ CURESOURCE;56[][] }}), MARKS_NUMBERS_1 <= CAST(MARKS_NUMBERS_1, {{ CURESOURCE;57[][] }}), HS_2 <= CAST(HS_2, {{ CURESOURCE;58[][] }}), CONTAINER_2 <= CAST(CONTAINER_2, {{ CURESOURCE;59[][] }}), PIECES_2 <= CAST(PIECES_2, {{ CURESOURCE;60[][] }}), DESCRIPTION_2 <= CAST(DESCRIPTION_2, {{ CURESOURCE;61[][] }}), HARMONIZED_2 <= CAST(HARMONIZED_2, {{ CURESOURCE;62[][] }}), MARKS_NUMBERS_2 <= CAST(MARKS_NUMBERS_2, {{ CURESOURCE;63[][] }}), HS_3 <= CAST(HS_3, {{ CURESOURCE;64[][] }}), CONTAINER_3 <= CAST(CONTAINER_3, {{ CURESOURCE;65[][] }}), PIECES_3 <= CAST(PIECES_3, {{ CURESOURCE;66[][] }}), DESCRIPTION_3 <= CAST(DESCRIPTmimir.algebra.TypeException: Type Mismatch [Numeric]: found any, but expected real DST()
	at mimir.algebra.Typechecker$.assertNumeric(Typechecker.scala:270)
	at mimir.algebra.function.GeoFunctions$$anonfun$register$2$$anonfun$apply$1.apply(GeoFunctions.scala:31)
	at mimir.algebra.function.GeoFunctions$$anonfun$register$2$$anonfun$apply$1.apply(GeoFunctions.scala:31)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at mimir.algebra.function.GeoFunctions$$anonfun$register$2.apply(GeoFunctions.scala:31)
	at mimir.algebra.function.GeoFunctions$$anonfun$register$2.apply(GeoFunctions.scala:30)
	at mimir.algebra.Typechecker.returnTypeOfFunction(Typechecker.scala:155)
	at mimir.algebra.Typechecker.typeOf(Typechecker.scala:129)
	at mimir.algebra.Typechecker$$anonfun$1.apply(Typechecker.scala:77)
	at mimir.algebra.Typechecker$$anonfun$1.apply(Typechecker.scala:77)
	at mimir.algebra.Typechecker$$anonfun$typeOf$2.apply(Typechecker.scala:129)
	at mimir.algebra.Typechecker$$anonfun$typeOf$2.apply(Typechecker.scala:129)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at mimir.algebra.Typechecker.typeOf(Typechecker.scala:129)
	at mimir.algebra.Typechecker$$anonfun$1.apply(Typechecker.scala:77)
	at mimir.algebra.Typechecker$$anonfun$1.apply(Typechecker.scala:77)
	at mimir.algebra.Typechecker.typeOf(Typechecker.scala:98)
	at mimir.algebra.Typechecker.assert(Typechecker.scala:60)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:195)
	at mimir.algebra.Typechecker.schemaOf(Typechecker.scala:175)
	at mimir.Mimir$.handleExplain(Mimir.scala:155)
	at mimir.Mimir$.eventLoop(Mimir.scala:105)
	at mimir.Mimir$.main(Mimir.scala:86)
	at mimir.Mimir.main(Mimir.scala)
ION_3, {{ CURESOURCE;67[][] }}), HARMONIZED_3 <= CAST(HARMONIZED_3, {{ CURESOURCE;68[][] }}), MARKS_NUMBERS_3 <= CAST(MARKS_NUMBERS_3, {{ CURESOURCE;69[][] }}), HS_4 <= CAST(HS_4, {{ CURESOURCE;70[][] }}), CONTAINER_4 <= CAST(CONTAINER_4, {{ CURESOURCE;71[][] }}), PIECES_4 <= CAST(PIECES_4, {{ CURESOURCE;72[][] }}), DESCRIPTION_4 <= CAST(DESCRIPTION_4, {{ CURESOURCE;73[][] }}), HARMONIZED_4 <= CAST(HARMONIZED_4, {{ CURESOURCE;74[][] }}), MARKS_NUMBERS_4 <= CAST(MARKS_NUMBERS_4, {{ CURESOURCE;75[][] }}), HS_5 <= CAST(HS_5, {{ CURESOURCE;76[][] }}), CONTAINER_5 <= CAST(CONTAINER_5, {{ CURESOURCE;77[][] }}), PIECES_5 <= CAST(PIECES_5, {{ CURESOURCE;78[][] }}), DESCRIPTION_5 <= CAST(DESCRIPTION_5, {{ CURESOURCE;79[][] }}), HARMONIZED_5 <= CAST(HARMONIZED_5, {{ CURESOURCE;80[][] }}), MARKS_NUMBERS_5 <= CAST(MARKS_NUMBERS_5, {{ CURESOURCE;81[][] }})](
                   CURESOURCE_RAW(DATE:varchar, MONTH:varchar, CONSIGNEE_DECLARED:varchar, CONSIGNEE_DECLARED_ADDRESS:varchar, SHIPPER_DECLARED:varchar, SHIPPER_ADDRESS:varchar, NOTIFY_NAME:varchar, NOTIFY_ADDRESS:varchar, CARRIER_CODE:varchar, CARRIER:varchar, BILL_MASTER_CARRIER:varchar, MASTER_CONSIGNEE_UNIFIED:varchar, MASTER_SHIPPER:varchar, MASTER_NOTIFY:varchar, CONSIGNEE_UNIFIED:varchar, SHIPPER_UNIFIED:varchar, CONSIGNEE_S_STATE:varchar, CONSIGNEE_S_CITY:varchar, CONSIGNEE_S_ZIP_CODE:varchar, BILL_OF_LADING_NBR:varchar, MASTER_HOUSE:varchar, MODE_OF_TRANSPORT:varchar, ESTIMATED_DATE:varchar, IN_BOND_ENTRY_TYPE:varchar, SHORT_CONTAINER_DESCRIPTION:varchar, IMO_CODE:varchar, HIGH_CUBE:varchar, BILL_MASTER:varchar, HS_1:varchar, HS_DESCRIPTION:varchar, FOREIGN_DESTINATION:varchar, US_REGION:varchar, WORLD_REGION_BY_PORT_OF_DEPARTURE:varchar, COUNTRY_BY_PORT_OF_DEPARTURE:varchar, PORT_OF_DEPARTURE:varchar, STATE_OF_ARRIVAL_PORT:varchar, PORT_OF_ARRIVAL:varchar, VESSEL:varchar, VESSEL_COUNTRY:varchar, FINAL_DESTINATION:varchar, COUNTRY_OF_ORIGIN:varchar, WORLD_REGION_BY_COUNTRY_OF_ORIGIN:varchar, PLACE_OF_RECEIPT:varchar, COUNTRY_BY_PLACE_OF_RECEIPT:varchar, WORLD_REGION_BY_PLACE_OF_RECEIPT:varchar, QUANTITY:varchar, QUANTITY_UNIT:varchar, WEIGHT:varchar, WEIGHT_UNIT:varchar, MEASURE:varchar, MEASURE_UNIT:varchar, CONTAINER_QUANTITY:varchar, METRIC_TONS:varchar, CONTAINER_1:varchar, PIECES_1:varchar, DESCRIPTION_1:varchar, HARMONIZED_1:varchar, MARKS_NUMBERS_1:varchar, HS_2:varchar, CONTAINER_2:varchar, PIECES_2:varchar, DESCRIPTION_2:varchar, HARMONIZED_2:varchar, MARKS_NUMBERS_2:varchar, HS_3:varchar, CONTAINER_3:varchar, PIECES_3:varchar, DESCRIPTION_3:varchar, HARMONIZED_3:varchar, MARKS_NUMBERS_3:varchar, HS_4:varchar, CONTAINER_4:varchar, PIECES_4:varchar, DESCRIPTION_4:varchar, HARMONIZED_4:varchar, MARKS_NUMBERS_4:varchar, HS_5:varchar, CONTAINER_5:varchar, PIECES_5:varchar, DESCRIPTION_5:varchar, HARMONIZED_5:varchar, MARKS_NUMBERS_5:varchar)
                 )
              )
            ),
            PROJECT[LOC_IMO_CODE <= IMO_CODE, LOC_LAT <= LAT, LOC_LON <= LON](
              CURELOCATIONS[] := (
                 PROJECT[IMO_CODE <= CAST(IMO_CODE, {{ CURELOCATIONS;0[][] }}), LAT <= CAST(LAT, {{ CURELOCATIONS;1[][] }}), LON <= CAST(LON, {{ CURELOCATIONS;2[][] }})](
                   CURELOCATIONS_RAW(IMO_CODE:varchar, LAT:varchar, LON:varchar)
                 )
              )
            )
          )
        ),
        PROJECT[PORTS_PORT <= PORT, PORTS_LAT <= LAT, PORTS_LON <= LON](
          CUREPORTS[] := (
             PROJECT[PORT <= CAST(PORT, {{ CUREPORTS;0[][] }}), LAT <= CAST(LAT, {{ CUREPORTS;1[][] }}), LON <= CAST(LON, {{ CUREPORTS;2[][] }})](
               CUREPORTS_RAW(PORT:varchar, LAT:varchar, LON:varchar)
             )
          )
        )
      )
    )
  )
)
An unknown error occurred...
```

**Comment by okennedy** [comment] 2017-08-01 14:41
I suspect I know what this is.  This shouldn't be a blocker, just means explain won't work for a little.  Give me a day or two to look it over.

**Comment by okennedy** [comment] 2017-08-01 17:27
As suspected... this isn't a blocker, just an issue with EXPLAIN.  A fix has been pushed.

**Closed by okennedy** 2017-08-01 17:27 UTC
