### ISSUE TITLE
Javascript error on explain.

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#22] opened 2015-07-20 03:51 UTC
![screen shot 2015-07-19 at 11 50 59 pm](https://cloud.githubusercontent.com/assets/3641553/8769690/134a513e-2e71-11e5-9c86-0d2c1ca05689.png)

**Comment by Legacy25** [comment] 2015-07-20 04:26
I'm not encountering this bug (no changes have been pushed since Friday's demo). Can I get a more detailed report of when it goes wrong? Is it intermittent or does it happen every time?

**Comment by okennedy** [comment] 2015-07-20 19:27
The above error comes up every single time I click to explain.

Debugging the expression, `res.result` exists and is a legitimate string.  I'll play a bit more with it in a little bit.

**Comment by Legacy25** [comment] 2015-07-20 20:10
This is a browser issue. ```startsWith``` is part of the EcmaScript 6 standard, which is pretty new. I think Safari doesn't have support for it. I'll change the implementation to not use ```startsWith```, should be simple enough.

**Comment by okennedy** [comment] 2015-07-20 21:02
Yes, this looks like it.  Safari does not support startsWith.

**Comment by okennedy** [comment] 2015-07-20 21:10
It looks like this line is part of the javascript that generates the vg-term list.  This code should go away when #20 is fixed, so imo just roll the fix into that.

**Comment by Legacy25** [comment] 2015-07-21 03:51
This issue has been addressed through a simple code addition from StackOverflow -
http://stackoverflow.com/questions/646628/how-to-check-if-a-string-startswith-another-string

Even though VGTerms listing is now server side, I am still using startsWith for error checking. I think the issue should be fixed now though. I will keep this open till that is confirmed, since I cannot test on Safari.

**Comment by okennedy** [comment] 2015-07-21 16:39
This seems like the wrong way to do it.  If you're getting structured data from the server, why not encode that data in a format with more clearly defined error semantics.  For example, using JSON:
```
{ "data": [ "TERM1", "TERM2", ... ], success: true }
```

**Comment by Legacy25** [comment] 2015-07-21 18:30
Done, errors now have their own class with their own json representation.

**Closed by Legacy25** 2015-07-21 18:30 UTC
Labels: bug, webview
