### ISSUE TITLE
Typechecker issue for SeriesMissingValueLens in ReadingsDemo branch

### ISSUE THREAD

**Issue by anandsan1** [UBOdin/mimir#276] opened 2017-10-23 14:25 UTC
![image](https://user-images.githubusercontent.com/29679762/31894361-380560a8-b7dc-11e7-9935-85cb43c76be2.png)

The error occurs when we try to access from the view created by the Missing Value Lens. There is a type-mis match between the VG-Term in THEN part and Column in the ELSE part
. 
For example: if my create lens statement is as below:

CREATE LENS TESTABC1 AS SELECT * FROM ABC WITH MISSING_VALUE ('COL2');

where table ABC is CREATE TABLE ABC1(Col1 VARCHAR, Col2 INT, Col3 INT);

Here {{ TESTABC1:INTERPOLATE;0[ROWID][ROWID] }} is returning the type of first column in SELECT * FROM ABC which is used as the input query to the lens

**Comment by okennedy** [comment] 2017-12-04 20:51
Duplicate of #269 
For now, set types in adaptive schemas before creating lenses.

**Closed by okennedy** 2017-12-04 20:51 UTC
Labels: duplicate
